#!/usr/bin/env expect

set timeout -1
set totp_profile "jumpserver"
set ssh_host "Jumpserver"

if {[info exists env(TOTP_PROFILE)] && $env(TOTP_PROFILE) ne ""} {
    set totp_profile $env(TOTP_PROFILE)
}

if {[info exists env(JUMPSERVER_SSH_HOST)] && $env(JUMPSERVER_SSH_HOST) ne ""} {
    set ssh_host $env(JUMPSERVER_SSH_HOST)
}

set otp [exec totp $totp_profile]
spawn ssh $ssh_host

expect {
    -re {(OTP Code\]|OTP|Verification code|验证码).*:?} {
        send "$otp\r"
        exp_continue
    }
    -re {(Opt>|\[Host\]>)} {
        interact
    }
}
